### ISSUE TITLE
group LW validation errors by route

### ISSUE THREAD

**Issue by stevethomas** [timacdonald/pulse-validation-errors#10]
This might be non-issue or a Pulse core issue, feel free to close.

<img width="671" alt="image" src="https://github.com/timacdonald/pulse-validation-errors/assets/1127412/04706767-62d2-4029-a072-55540e089477">

This validation error is triggered on a product route, and we have about a gazillion of those, so i'm not really getting a complete picture of total occurrences. It might also exhaust the whole `->take(100)` with similar style errors without grouping.  

Is it feasible to group these occurrences under `products/{product}` route? This logic does not appear to apply to `livewire/update` endpoint.

**Comment by timacdonald** [comment]
This will be implemented in https://github.com/timacdonald/pulse-validation-errors/pull/11.

Will likely tag this one next week once Pulse tags a new version, as I made some changes there that we will depend on.
