### ISSUE TITLE
Suggestion: Ignore specific fields

### ISSUE THREAD

**Issue by ziming** [timacdonald/pulse-validation-errors#13]
Will be nice if can ignore specific fields too, for example a register form may have many other fields but i just want to ignore the password field since the by far the highest validation error on my site is "Your password has appeared in a data leak" during registration

**Comment by timacdonald** [comment]
Hi there,

This is already possible with Pulse's built in filtering feature. I've just updated the docs to include an example for you.

https://github.com/timacdonald/pulse-validation-errors?tab=readme-ov-file#ignore-specific-error-messages

**Comment by ziming** [comment]
Hi @timacdonald 

I tried what you added in the docs. 2 days later, my Pulse dashboard is empty & recording nothing. I think there is some mistake with the provided code (the Pulse::filter)

Once I commented it out, everything starts recording again (including the validation error that I wanted to ignore)

```php
Pulse::filter(fn (Entry $entry) => match ($entry->type) {
            'validation_error' => ! Str::contains($entry->key, [
                'password has appeared in a data leak.',
            ]),
        });
```

Thank you

**Comment by ziming** [comment]
ah okay i figure out the issue, because there is is default fallback to return true
