### ISSUE TITLE
Feature request: Group localized errors when using multiple languages

### ISSUE THREAD

**Issue by jhm-ciberman** [timacdonald/pulse-validation-errors#27]
Hello. First, thanks for this amazing package. It is super useful to see what our users are doing in real time. I want to ask if this is already supported or if it could be added as a new feature: 

Our app is localized to 11 languages, and counting:
```
'cs', // Czech
'de', // German
'es', // Spanish
'en', // English
'fr', // French
'ja', // Japanese
'ko', // Korean
'pl', // Polish
'pt', // Portuguese
'ru', // Russian
'zh_CN', // Chinese (Simplified)
```
This means, every validation error is collected in multiple languages. For example, this is the same validation error, but in 3 different languages:

![image](https://github.com/user-attachments/assets/7099b706-ea2f-47c6-bffd-031d6165fa19)

Would it be any way to group them automatically? Not by hand, because that's super error prone.

**Comment by timacdonald** [comment]
Unfortunately not.

I would turning off message capture which will at least tell you which endpoints are impacted the most.

```php
// file: config/pulse.php

return [
    // ...

    'recorders' => [
        TiMacDonald\Pulse\Recorders\ValidationErrors::class => [
            // ...
            'capture_messages' => false,
        ],
    ],
];
```

You could also create a middleware to turn message capture on for specific routes if you are having troubles working out which inputs are problematic.

**Comment by jhm-ciberman** [comment]
I imagined that. No problem. I understand. It was just something nice to have, not a necessity. 

Thanks for this amazing package!
