### ISSUE TITLE
is validation from livewire components recorded?

### ISSUE THREAD

**Issue by ziming** [timacdonald/pulse-validation-errors#4]
Thanks for making this useful package. I used it right away on some of my sites.

However I notice that none of the validation errors come from my livewire components (both filament & normal livewire components). It is all coming from traditional controllers so far

So i wanted to ask if this package support recording validation errors from livewire components and if not, is there a future plan to support it?

Thank you

**Comment by timacdonald** [comment]
Livewire validation errors are not currently captured.

Would love to support Livewire, but as I don't run any Livewire applications myself I didn't add it for the initial release.

Would certainly be open to supporting Livewire.

**Comment by timacdonald** [comment]
Thanks to @riasvdv Livewire validation errors are now supported 🥳
